# spawn-position: The coordinates of the lobby position
lobby-spawn-position:
  spawn-x: 0.5
  spawn-y: 0
  spawn-z: 0.5
  spawn-world: world
lobby-region:
  x1: 0
  y1: 0
  z1: 0
  x2: 0
  y2: 0
  z2: 0
startdoornames:
  - exampledoor1
  - exampledoor2
  - exampledoor3
  - exampledoor4

