name: HungerGamesPlus
version: '${project.version}'
main: hgplus.HungerGamesPlus2
api-version: 1.20
authors: [ coolspee, Jbeast291 ]
commands:
  hgplus:
    description: Hunger Games Plus Command
    permission: hungergamesplus.admin